on: [pull_request]

jobs:
  build_docker_compose_job:
    runs-on: ubuntu-latest
    name: build docker-compose binaries
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker build arm32v7
        run: make image.arm32v7
      - name: docker build arm64v8
        run: make image.arm64v8
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: docker-compose-binaries
          path: dist/

