on:
  release:
    types: [created]

name: Upload release assets after release is created
jobs:
  build:
    name: build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: build
        run: make image.arm64v8 image.arm32v7
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: dist/

  upload:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v1
        with:
          name: binaries
          path: dist/

      - name: Upload release assets
        uses: skx/github-action-publish-binaries@9f2ea568baec5017a7d608f03ef143a57745cc5c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './dist/*'
